// <auto-generated />
namespace Biblioteca.Livros.Dados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MigracaoADDEditora : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigracaoADDEditora));
        
        string IMigrationMetadata.Id
        {
            get { return "202011141423584_MigracaoADDEditora"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
