// <auto-generated />
namespace Biblioteca.Livros.Dados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddLivro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLivro));
        
        string IMigrationMetadata.Id
        {
            get { return "202011151346272_AddLivro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
